# PharmMS Setup - building the distributable installer.
#
#   .\build_installer.ps1                     full build: app + setup
#   .\build_installer.ps1 -SkipAppBuild       rebuild only the setup wrapper
#
# Produces:  dist\PharmMS-Setup.exe
#
# HOW THIS WORKS
# --------------
# Rather than depend on Inno Setup being installed on the build machine, the
# setup is assembled here: the application payload is embedded as a base64 blob
# inside a PowerShell script, and that script is compiled into a real .exe with
# the .NET C# compiler that ships with Windows. The result is a single
# double-clickable installer with no prerequisites on either side.
#
# What the installer does on the target machine:
#   * shows a short wizard (welcome -> folder -> progress -> finish)
#   * verifies the payload hash before writing anything
#   * installs to %LOCALAPPDATA%\Programs\PharmMS (no admin rights needed)
#   * creates Desktop + Start Menu shortcuts
#   * optionally launches the app when finished
#   * registers a normal uninstaller under Apps & features

[CmdletBinding()]
param(
    [switch]$SkipAppBuild
)

$ErrorActionPreference = 'Stop'
# See the note in build_exe.ps1: GitHub Actions runs `shell: pwsh` (PowerShell 7),
# where a native command writing to stderr raises a terminating
# NativeCommandError under 'Stop'. npm and pip both write progress there, so a
# perfectly good build could abort on a deprecation notice. Real failures are
# still caught, because every caller below checks its exit code or the artefact
# it expects.
$PSNativeCommandUseErrorActionPreference = $false

$BackendDir   = $PSScriptRoot
$PayloadExe   = Join-Path $BackendDir 'dist\PharmMS.exe'
$BuildStage = Join-Path $BackendDir 'build\installer'
$SetupPs1 = Join-Path $BuildStage 'setup.ps1'
$SetupCs = Join-Path $BuildStage 'stub.cs'
$OutSetup = Join-Path $BackendDir 'dist\PharmMS-Setup.exe'

function Write-Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Fail($m) { Write-Host "ERROR: $m" -ForegroundColor Red; exit 1 }

# --- 1. Build the application payload ---------------------------------------
if (-not $SkipAppBuild) {
    Write-Step 'Building the application payload'
    # The script is invoked with the call operator and judged by the artefact it
    # is supposed to produce, NOT by $LASTEXITCODE.
    #
    # $LASTEXITCODE reflects the last *native* command to run, and it survives
    # the call - so after a successful build it still held the exit code of
    # whatever program ran last inside build_exe.ps1 (a python or pip call).
    # The build would finish, print "Build complete", and then be reported as
    # "ERROR: Application build failed" immediately afterwards, because the
    # stale code happened to be non-zero. Checking the output is both correct
    # and the thing we actually care about.
    & (Join-Path $BackendDir 'build_exe.ps1')
    if (-not (Test-Path $PayloadExe)) {
        Fail "Application build did not produce $PayloadExe"
    }
}

if (-not (Test-Path $PayloadExe)) {
    Fail "Payload not found: $PayloadExe. Run build_exe.ps1 first."
}

$payloadBytes = [IO.File]::ReadAllBytes($PayloadExe)
$payloadB64 = [Convert]::ToBase64String($payloadBytes)
$payloadHash = (Get-FileHash $PayloadExe -Algorithm SHA256).Hash
$payloadMb = [math]::Round($payloadBytes.Length / 1MB, 1)

Write-Host "    payload: $payloadMb MB, sha256 $($payloadHash.Substring(0,16))..."

# --- 2. Assemble the setup script -------------------------------------------
Write-Step 'Assembling the setup script'
New-Item -ItemType Directory -Path $BuildStage -Force | Out-Null

$appVersion = '2.0.0'
$template = @'
# PharmMS Setup - self-contained installer.
# Generated by build_installer.ps1. Do not edit by hand.

$ErrorActionPreference = 'Stop'

$AppName     = 'Pharmacy Management System'
$ShortName   = 'PharmMS'
$Version     = '__VERSION__'
$Publisher   = 'Jayant'
$PayloadHash = '__HASH__'
$PayloadB64  = '__PAYLOAD__'

$InstallDir  = Join-Path $env:LOCALAPPDATA 'Programs\PharmMS'
$DataDir     = Join-Path $env:LOCALAPPDATA 'PharmMS'
$StartMenu   = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
$DesktopDir  = [Environment]::GetFolderPath('Desktop')
$ExeName     = "$ShortName.exe"

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# ---------------------------------------------------------------- UI helpers --
function New-Dialog($text, $title, $buttons) {
    $form = New-Object Windows.Forms.Form
    $form.Text = $title
    $form.Size = New-Object Drawing.Size(520, 250)
    $form.StartPosition = 'CenterScreen'
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.BackColor = [Drawing.Color]::White
    $form.Font = New-Object Drawing.Font('Segoe UI', 9)

    $label = New-Object Windows.Forms.Label
    $label.Text = $text
    $label.Location = New-Object Drawing.Point(22, 20)
    $label.Size = New-Object Drawing.Size(465, 130)
    $form.Controls.Add($label)

    $result = [Windows.Forms.DialogResult]::Cancel
    $x = 470 - (($buttons.Count) * 108)
    foreach ($b in $buttons) {
        $btn = New-Object Windows.Forms.Button
        $btn.Text = $b.Text
        $btn.Size = New-Object Drawing.Size(100, 30)
        $btn.Location = New-Object Drawing.Point($x,165)
        $btn.FlatStyle = 'System'
        $btn.Add_Click({ param($s, $e) $script:dialogResult = $s.Tag; $form.Close() })
        $btn.Tag = $b.Value
        $form.Controls.Add($btn)
        $x += 108
    }
    $form.AcceptButton = $form.Controls | Where-Object { $_ -is [Windows.Forms.Button] } | Select-Object -First 1
    $form.ShowDialog() | Out-Null
    return $script:dialogResult
}

function Show-ProgressForm($totalBytes) {
    $form = New-Object Windows.Forms.Form
    $form.Text = "$AppName - Setup"
    $form.Size = New-Object Drawing.Size(520, 190)
    $form.StartPosition = 'CenterScreen'
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.ControlBox = $false
    $form.BackColor = [Drawing.Color]::White
    $form.Font = New-Object Drawing.Font('Segoe UI', 9)

    $label = New-Object Windows.Forms.Label
    $label.Text = 'Preparing...'
    $label.Location = New-Object Drawing.Point(22, 20)
    $label.Size = New-Object Drawing.Size(465, 20)
    $form.Controls.Add($label)

    $bar = New-Object Windows.Forms.ProgressBar
    $bar.Location = New-Object Drawing.Point(22, 48)
    $bar.Size = New-Object Drawing.Size(465, 22)
    $bar.Minimum = 0
    $bar.Maximum = [Math]::Max(1, [int]($totalBytes / 1024))
    $form.Controls.Add($bar)

    $detail = New-Object Windows.Forms.Label
    $detail.Text = ''
    $detail.Location = New-Object Drawing.Point(22, 78)
    $detail.Size = New-Object Drawing.Size(465, 40)
    $detail.ForeColor = [Drawing.Color]::FromArgb(90, 90, 90)
    $form.Controls.Add($detail)

    $form.Show()
    $form.Refresh()
    return @{ Form = $form; Bar = $bar; Label = $label; Detail = $detail }
}

function Update-Progress($ui, $message, $value) {
    if (-not $ui) { return }
    # $value = -1 means "no measurable progress" - update the label only.
    # A ProgressBar rejects any Value below Minimum, so the comparison must
    # guard the assignment itself, not sit inside it.
    $ui.Label.Text = $message
    if ($value -ge 0) {
        $clamped = [Math]::Max($ui.Bar.Minimum, [Math]::Min($ui.Bar.Maximum, [int]$value))
        $ui.Bar.Value = $clamped
    }
    $ui.Form.Refresh()
    [Windows.Forms.Application]::DoEvents()
}

# ------------------------------------------------------- headless detection --
# A GUI cannot always be shown: silent/automated installs run with -Silent,
# and some execution contexts have no interactive desktop at all. In those
# cases the install still completes and the wizard is simply skipped, rather
# than the installer opening nothing and appearing to do nothing.
$Silent = $false
if ($args -contains '-Silent' -or $env:PHARMS_SILENT -eq '1') { $Silent = $true }

function Test-CanShowGui {
    try {
        $null = [Windows.Forms.SystemInformation]::UserInteractive
        # Creating and disposing a form proves a window station is usable.
        $probe = New-Object Windows.Forms.Form
        $probe.Dispose()
        return $true
    } catch {
        return $false
    }
}

if (-not $Silent -and -not (Test-CanShowGui)) {
    Write-Host "No interactive desktop available - running silently."
    $Silent = $true
}

# ------------------------------------------------------------------- wizard --
$welcome = @"
This will install $AppName version $Version on your computer.

  - Installs to your user folder (no administrator rights needed)
  - Adds shortcuts to your Desktop and Start Menu
  - Keeps all patient records in $DataDir
  - Works completely offline

Your records are stored outside the program folder, so reinstalling
or upgrading later will never delete your data.

Click Install to continue.
"@

if (-not $Silent) {
    $choice = New-Dialog $welcome "$AppName Setup" @(
        @{ Text = 'Cancel';  Value = 'cancel' },
        @{ Text = 'Install'; Value = 'install' }
    )
    if ($choice -ne 'install') { exit 0 }
}

# ---------------------------------------------------------------- installing --
$ui = $null
if (-not $Silent) { $ui = Show-ProgressForm ($PayloadB64.Length) }
try {
    Update-Progress $ui 'Verifying the installer payload...' -1

    # Decode and verify before touching the disk.
    $bytes = [Convert]::FromBase64String($PayloadB64)
    $sha = [Security.Cryptography.SHA256]::Create()
    $actual = ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-', '')
    if ($actual -ne $PayloadHash) {
        $ui.Form.Close()
        [Windows.Forms.MessageBox]::Show(
            "The installer payload failed its integrity check and was not written." +
            "`n`nThis usually means the download was incomplete or corrupted." +
            "`nPlease download the setup file again.",
            "$AppName Setup", 'OK', 'Error') | Out-Null
        exit 1
    }
    Update-Progress $ui 'Payload verified.' 10

    # Close a running copy so the file is not locked.
    Get-Process $ShortName -ErrorAction SilentlyContinue | ForEach-Object {
        Update-Progress $ui 'Closing a running copy...' -1
        $_.CloseMainWindow() | Out-Null
        Start-Sleep -Milliseconds 700
        if (-not $_.HasExited) { $_.Kill() }
    }

    Update-Progress $ui "Creating $InstallDir..." 20
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

    Update-Progress $ui 'Writing application files...' 60
    $target = Join-Path $InstallDir $ExeName
    [IO.File]::WriteAllBytes($target, $bytes)
    Update-Progress $ui 'Application files written.' 85

    # Shortcuts
    Update-Progress $ui 'Creating shortcuts...' 90
    $shell = New-Object -ComObject WScript.Shell
    foreach ($lnkPath in @(
        (Join-Path $DesktopDir "$ShortName.lnk"),
        (Join-Path $StartMenu "$ShortName.lnk")
    )) {
        $lnk = $shell.CreateShortcut($lnkPath)
        $lnk.TargetPath = $target
        $lnk.WorkingDirectory = $InstallDir
        $lnk.IconLocation = $target
        $lnk.Description = $AppName
        $lnk.Save()
    }
    Update-Progress $ui 'Shortcuts created.' 95

    # Uninstaller + Add/Remove Programs entry
    Update-Progress $ui 'Registering the uninstaller...' 97
    $uninstallerPath = Join-Path $InstallDir 'Uninstall-PharmMS.ps1'
    $uninstaller = @"
`$ErrorActionPreference = 'SilentlyContinue'
`$ShortName = '$ShortName'
`$InstallDir = '$InstallDir'
`$DataDir = '$DataDir'
Get-Process `$ShortName | ForEach-Object { `$_.CloseMainWindow() | Out-Null; Start-Sleep -Milliseconds 700; if (-not `$_.HasExited) { `$_.Kill() } }
Remove-Item (Join-Path ([Environment]::GetFolderPath('Desktop')) "`$ShortName.lnk") -Force
Remove-Item (Join-Path `$env:APPDATA 'Microsoft\Windows\Start Menu\Programs' "`$ShortName.lnk") -Force
Remove-Item 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS' -Force -ErrorAction SilentlyContinue
Remove-Item 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS' -Force -ErrorAction SilentlyContinue
Remove-Item `$InstallDir -Recurse -Force
Add-Type -AssemblyName System.Windows.Forms
`$answer = [Windows.Forms.MessageBox]::Show(
    "PharmMS has been removed.`n`nAlso delete all patient records in:`n`$DataDir ?`n`nThis cannot be undone.",
    'PharmMS Uninstall', 'YesNo', 'Warning')
if (`$answer -eq 'Yes') {
    Remove-Item `$DataDir -Recurse -Force
} else {
    [Windows.Forms.MessageBox]::Show("Your records were kept at:`n`$DataDir", 'PharmMS Uninstall', 'OK', 'Information') | Out-Null
}
"@
    Set-Content -Path $uninstallerPath -Value $uninstaller -Encoding UTF8

    $uninstallCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$uninstallerPath`""
    $key = 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS'
    New-Item -Path $key -Force | Out-Null
    Set-ItemProperty -Path $key -Name 'DisplayName'     -Value $AppName
    Set-ItemProperty -Path $key -Name 'DisplayVersion'  -Value $Version
    Set-ItemProperty -Path $key -Name 'Publisher'       -Value $Publisher
    Set-ItemProperty -Path $key -Name 'DisplayIcon'     -Value $target
    Set-ItemProperty -Path $key -Name 'InstallLocation' -Value $InstallDir
    Set-ItemProperty -Path $key -Name 'UninstallString' -Value $uninstallCmd
    Set-ItemProperty -Path $key -Name 'NoModify'        -Value 1 -Type DWord
    Set-ItemProperty -Path $key -Name 'NoRepair'        -Value 1 -Type DWord
    try {
        $size = [math]::Round((Get-Item $target).Length / 1024)
        Set-ItemProperty -Path $key -Name 'EstimatedSize' -Value $size -Type DWord
    } catch { }

    Update-Progress $ui 'Finishing...' 100
}
finally {
    if ($ui) {
        $ui.Form.Close()
        $ui.Form.Dispose()
    }
}

# ------------------------------------------------------------------- finish --
$sizeMb = [math]::Round((Get-Item (Join-Path $InstallDir $ExeName)).Length / 1MB, 1)

$done = @"
$AppName $Version has been installed.

  Program : $InstallDir\$ExeName  ($sizeMb MB)
  Records : $DataDir\pharmacy.db

You can start it from the Desktop shortcut "$ShortName" or from the
Start Menu. It opens in its own window and works without an
internet connection.

Would you like to start $ShortName now?
"@

if ($Silent) {
    Write-Host "Installed $AppName $Version to $InstallDir"
} else {
    $run = New-Dialog $done "$AppName Setup - Complete" @(
        @{ Text = 'Finish'; Value = 'finish' },
        @{ Text = 'Launch'; Value = 'launch' }
    )
    if ($run -eq 'launch') {
        Start-Process (Join-Path $InstallDir $ExeName) -WorkingDirectory $InstallDir
    }
}
'@

$setupScript = $template.Replace('__VERSION__', $appVersion).
Replace('__HASH__', $payloadHash).
Replace('__PAYLOAD__', $payloadB64)

Set-Content -Path $SetupPs1 -Value $setupScript -Encoding UTF8
Write-Host "    setup script: $([math]::Round((Get-Item $SetupPs1).Length / 1MB, 1)) MB"

# --- 3. Compile a launcher .exe ---------------------------------------------
Write-Step 'Compiling the installer executable'

# A tiny C# stub that runs the embedded PowerShell script. Compiled with the
# C# compiler that ships with the .NET Framework, so no extra tooling is needed.
$stub = @'
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;

class PharmMSSetup
{
    [STAThread]
    static int Main(string[] args)
    {
        try
        {
            string temp = Path.Combine(Path.GetTempPath(), "PharmMS-Setup-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(temp);
            string script = Path.Combine(temp, "setup.ps1");

            // The setup script is embedded beside the stub as a resource.
            Assembly self = Assembly.GetExecutingAssembly();
            string[] names = self.GetManifestResourceNames();
            string resource = null;
            foreach (string n in names)
            {
                if (n.EndsWith("setup.ps1", StringComparison.OrdinalIgnoreCase)) { resource = n; break; }
            }
            if (resource == null)
            {
                Console.Error.WriteLine("Internal error: setup payload missing.");
                return 2;
            }

            using (Stream s = self.GetManifestResourceStream(resource))
            using (StreamReader r = new StreamReader(s, Encoding.UTF8))
            {
                File.WriteAllText(script, r.ReadToEnd(), new UTF8Encoding(false));
            }

            // Resolve PowerShell by ABSOLUTE PATH. A bare "powershell.exe" is
            // not reliable: it is absent from PATH on some machines (including
            // the one this was built on), which makes the installer exit
            // silently with no window and no error message.
            string ps = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.System),
                @"WindowsPowerShell\v1.0\powershell.exe");
            if (!File.Exists(ps))
            {
                ps = "powershell.exe";
            }

            // Forward command-line arguments (notably -Silent) to the script.
            // Without this the wizard always appears and an automated install
            // hangs waiting for a click that never comes.
            StringBuilder forwarded = new StringBuilder();
            foreach (string a in args)
            {
                if (forwarded.Length > 0) { forwarded.Append(' '); }
                forwarded.Append('"').Append(a.Replace("\"", "\\\"")).Append('"');
            }

            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = ps;
            psi.UseShellExecute = false;
            psi.Arguments = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"" + script + "\" " + forwarded.ToString();

            Process p = Process.Start(psi);
            p.WaitForExit();

            try { Directory.Delete(temp, true); } catch { }
            return p.ExitCode;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
            return 1;
        }
    }
}
'@

Set-Content -Path $SetupCs -Value $stub -Encoding UTF8

# .NET Framework's csc.exe is present on every Windows machine.
$csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $csc)) {
    $csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319\csc.exe'
}
if (-not (Test-Path $csc)) {
    Fail 'Could not find the C# compiler (csc.exe). A .NET Framework install is required to build the installer.'
}

$iconPath = Join-Path $BackendDir 'pharms.ico'

# The icon is a source asset, but a build should not die because one optional
# decoration is missing - csc.exe rejects a bad or absent path outright with
# "CS1583: not a valid Win32 resource file", which is a confusing way to be told
# the icon is simply not there. Warn and build without it instead, so the only
# consequence of a missing icon is a generic icon on the shortcut.
$iconArgs = @()
if (Test-Path $iconPath) {
    # The switch and its value must be ONE command-line token, because csc.exe
    # expects "/win32icon:path" and treats a separated path as an extra,
    # unconsumed argument:
    #
    #     fatal error CS2005: Missing file specification for '/win32icon:' option
    #
    # Two earlier attempts got this wrong in opposite directions:
    #   @("/win32icon:`"$iconPath`"")   literal quotes -> CS2021 invalid filename
    #   @('/win32icon:', $iconPath)      split token  -> CS2005 missing file
    #
    # Joining them into a single array element is the form that works on both
    # PowerShell 5.1 and 7: the runtime quotes the element as a whole, so the
    # space-free path needs no quoting and no quote character ever reaches csc.
    $iconArgs = @("/win32icon:$iconPath")
} else {
    Write-Host "    WARNING: $iconPath not found - building without a custom icon." -ForegroundColor Yellow
}

Push-Location $BuildStage
try {
    # /out and /resource are written as single tokens with the value inside the
    # string, which is safe because the quotes there are PowerShell syntax and
    # are removed before the argument is built. The icon is passed through
    # $iconArgs instead, precisely to avoid hand-written quoting.
    & $csc /nologo /target:winexe `
        "/out:$OutSetup" `
        "/resource:$SetupPs1,setup.ps1" `
        @iconArgs `
        /reference:System.dll `
        /reference:System.Windows.Forms.dll `
        "$SetupCs"
    if ($LASTEXITCODE -ne 0) { Fail 'csc.exe failed to compile the installer.' }
}
finally {
    Pop-Location
}

if (-not (Test-Path $OutSetup)) { Fail "Installer was not produced at $OutSetup" }

# --- 4. Report ---------------------------------------------------------------
$setupMb = [math]::Round((Get-Item $OutSetup).Length / 1MB, 1)

Write-Host ''
Write-Host '==============================================================' -ForegroundColor Green
Write-Host '  Installer built' -ForegroundColor Green
Write-Host '==============================================================' -ForegroundColor Green
Write-Host "  Setup file : $OutSetup"
Write-Host "  Size       : $setupMb MB"
Write-Host ''
Write-Host '  Upload this ONE file to GitHub Releases. Anyone can then'
Write-Host '  download and run it - no Python, no Node.js, no admin'
Write-Host '  rights, no internet connection required.'
Write-Host '==============================================================' -ForegroundColor Green
