# PharmMS Setup - the small web bootstrapper.
#
#   .\build_bootstrapper.ps1                          full build
#   .\build_bootstrapper.ps1 -SkipAppBuild            reuse dist\PharmMS.exe
#   .\build_bootstrapper.ps1 -Version 2.2.0           stamp a version
#
# Produces:  dist\PharmMS-Setup.exe   (a few hundred KB, NOT 15 MB)
#
# WHY THIS REPLACES THE EMBEDDED-PAYLOAD INSTALLER
# ------------------------------------------------
# The previous installer embedded the whole ~15 MB application as a base64 blob
# inside a PowerShell script and compiled that into the .exe. It worked and
# needed no internet, but it had two costs that turned out to matter more:
#
#   1. Every release carried a 15 MB download for a 15 MB app, and GitHub
#      Releases stored a third copy. Twelve releases is 180 MB of storage just
#      to deliver the same payload.
#   2. The version the user installed could NOT be changed after the fact. Once
#      the .exe was built, that was the bytes you got - there was no way to
#      re-pull a rebuilt payload, and a corrupted download meant starting over.
#
# So this is a bootstrapper: a tiny .exe that carries no application code at all,
# only the knowledge of WHERE to get it. It downloads the payload from the
# GitHub Release at install time, verifies its SHA-256 against a value baked
# into this file, and only then installs. The result:
#
#   * the download is ~200 KB instead of ~15 MB
#   * the payload is fetched over HTTPS from GitHub, and a tampered or truncated
#     download fails the hash check and is refused rather than installed
#   * progress is real - it reports megabytes received, not a fake bar
#   * the same small .exe can install any released version (`-Tag v2.3.0`)
#
# TRADE-OFF, STATED PLAINLY
# -------------------------
# This installer REQUIRES an internet connection, and it depends on GitHub being
# reachable. The embedded-payload installer did not. That is a deliberate
# exchange: a 200 KB download that needs the network, instead of a 15 MB
# download that does not. build_installer.ps1 is kept for anyone who needs the
# offline variant; both produce a file with the same name, so run one or the
# other, not both.

[CmdletBinding()]
param(
    [switch]$SkipAppBuild,
    [string]$Version = '2.2.0',
    [string]$Repository = 'Storm-21/Pharm_MS',
    [string]$Tag = 'latest'
)

$ErrorActionPreference = 'Stop'
# See the note in build_exe.ps1: GitHub Actions runs `shell: pwsh` (PowerShell 7),
# where a native command writing to stderr raises a terminating
# NativeCommandError under 'Stop'. npm and pip both write progress there, so a
# perfectly good build could abort on a deprecation notice.
$PSNativeCommandUseErrorActionPreference = $false

$BackendDir = $PSScriptRoot
$PayloadExe = Join-Path $BackendDir 'dist\PharmMS.exe'
$BuildStage = Join-Path $BackendDir 'build\bootstrapper'
$SetupPs1   = Join-Path $BuildStage 'bootstrap.ps1'
$StubCs     = Join-Path $BuildStage 'stub.cs'
$OutSetup   = Join-Path $BackendDir 'dist\PharmMS-Setup.exe'

function Write-Step($m) { Write-Host "==> $m" -ForegroundColor Cyan }
function Fail($m) { Write-Host "ERROR: $m" -ForegroundColor Red; exit 1 }

# --- 1. Build the application payload ---------------------------------------
# The payload is built here but NOT embedded. It is uploaded to the Release
# separately, and this installer downloads it. Building it now is what lets the
# script compute the expected SHA-256 and bake that in - so the bootstrapper
# refuses a payload that does not match the one it was built against.
if (-not $SkipAppBuild) {
    Write-Step 'Building the application payload'
    & (Join-Path $BackendDir 'build_exe.ps1')
    if (-not (Test-Path $PayloadExe)) {
        Fail "Application build did not produce $PayloadExe"
    }
}

if (-not (Test-Path $PayloadExe)) {
    Fail "Payload not found: $PayloadExe. Run build_exe.ps1 first."
}

$payloadBytes = [IO.File]::ReadAllBytes($PayloadExe)
$payloadHash = (Get-FileHash $PayloadExe -Algorithm SHA256).Hash
$payloadMb = [math]::Round($payloadBytes.Length / 1MB, 1)
$payloadName = 'PharmMS.exe'

Write-Host "    payload: $payloadMb MB, sha256 $($payloadHash.Substring(0, 16))..."

# The download URL is pinned to the release ASSET path, which is what the
# landing page links to. 'latest' resolves to the newest release, so a user who
# downloads the bootstrapper once still gets the current build.
if ($Tag -eq 'latest') {
    $downloadUrl = "https://github.com/$Repository/releases/latest/download/$payloadName"
} else {
    $downloadUrl = "https://github.com/$Repository/releases/download/$Tag/$payloadName"
}

# --- 2. Assemble the bootstrap script ---------------------------------------
Write-Step 'Assembling the bootstrap script'
New-Item -ItemType Directory -Path $BuildStage -Force | Out-Null

$template = @'
# PharmMS Setup - web bootstrapper.
# Generated by build_bootstrapper.ps1. Do not edit by hand.
#
# This file carries NO application code. It knows only where to fetch the
# payload and what hash to expect. See build_bootstrapper.ps1 for why.

$ErrorActionPreference = 'Stop'

$AppName     = 'Pharmacy Management System'
$ShortName   = 'PharmMS'
$Version     = '__VERSION__'
$Publisher   = 'Jayant'
$PayloadHash = '__HASH__'
$PayloadName = '__PAYLOAD_NAME__'
$DownloadUrl = '__URL__'
$Repository  = '__REPO__'
$Tag         = '__TAG__'

$InstallDir  = Join-Path $env:LOCALAPPDATA 'Programs\PharmMS'
$DataDir     = Join-Path $env:LOCALAPPDATA 'PharmMS'
$StartMenu   = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs'
$DesktopDir  = [Environment]::GetFolderPath('Desktop')
$ExeName     = "$ShortName.exe"

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# ---------------------------------------------------------------- UI helpers --
function New-Dialog($text, $title, $buttons) {
    $form = New-Object Windows.Forms.Form
    $form.Text = $title
    $form.Size = New-Object Drawing.Size(560, 290)
    $form.StartPosition = 'CenterScreen'
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.BackColor = [Drawing.Color]::White
    $form.Font = New-Object Drawing.Font('Segoe UI', 9)

    $label = New-Object Windows.Forms.Label
    $label.Text = $text
    $label.Location = New-Object Drawing.Point(22, 20)
    $label.Size = New-Object Drawing.Size(505, 175)
    $form.Controls.Add($label)

    $x = 510 - (($buttons.Count) * 108)
    foreach ($b in $buttons) {
        $btn = New-Object Windows.Forms.Button
        $btn.Text = $b.Text
        $btn.Size = New-Object Drawing.Size(100, 30)
        $btn.Location = New-Object Drawing.Point($x, 205)
        $btn.FlatStyle = 'System'
        $btn.Add_Click({ param($s, $e) $script:dialogResult = $s.Tag; $form.Close() })
        $btn.Tag = $b.Value
        $form.Controls.Add($btn)
        $x += 108
    }
    $form.AcceptButton = $form.Controls |
        Where-Object { $_ -is [Windows.Forms.Button] } | Select-Object -First 1
    $script:dialogResult = [Windows.Forms.DialogResult]::Cancel
    $form.ShowDialog() | Out-Null
    return $script:dialogResult
}

function Show-ProgressForm {
    $form = New-Object Windows.Forms.Form
    $form.Text = "$AppName - Setup"
    $form.Size = New-Object Drawing.Size(560, 210)
    $form.StartPosition = 'CenterScreen'
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false
    $form.MinimizeBox = $false
    $form.ControlBox = $false
    $form.BackColor = [Drawing.Color]::White
    $form.Font = New-Object Drawing.Font('Segoe UI', 9)

    $label = New-Object Windows.Forms.Label
    $label.Text = 'Preparing...'
    $label.Location = New-Object Drawing.Point(22, 20)
    $label.Size = New-Object Drawing.Size(505, 20)
    $form.Controls.Add($label)

    $bar = New-Object Windows.Forms.ProgressBar
    $bar.Location = New-Object Drawing.Point(22, 48)
    $bar.Size = New-Object Drawing.Size(505, 22)
    $bar.Minimum = 0
    $bar.Maximum = 1000
    $form.Controls.Add($bar)

    $detail = New-Object Windows.Forms.Label
    $detail.Text = ''
    $detail.Location = New-Object Drawing.Point(22, 80)
    $detail.Size = New-Object Drawing.Size(505, 60)
    $detail.ForeColor = [Drawing.Color]::FromArgb(90, 90, 90)
    $form.Controls.Add($detail)

    $form.Show()
    $form.Refresh()
    return @{ Form = $form; Bar = $bar; Label = $label; Detail = $detail }
}

function Update-Progress($ui, $message, $fraction, $detail) {
    if (-not $ui) { return }
    # $fraction = -1 means "no measurable progress" - update the labels only.
    # A ProgressBar rejects any Value below Minimum, so the comparison has to
    # guard the assignment itself rather than sit inside it.
    $ui.Label.Text = $message
    if ($PSBoundParameters.ContainsKey('detail') -and $null -ne $detail) {
        $ui.Detail.Text = $detail
    }
    if ($fraction -ge 0) {
        $clamped = [Math]::Max(0, [Math]::Min(1000, [int]($fraction * 1000)))
        $ui.Bar.Value = $clamped
    }
    $ui.Form.Refresh()
    [Windows.Forms.Application]::DoEvents()
}

# Removes shortcuts that point at a program which is not installed.
#
# WHY: an earlier installer left a desktop shortcut behind after a failed or
# partial install. The shortcut survives, its target does not, and the user is
# left clicking an icon that Windows answers with "the item was not found".
# Clearing only the BROKEN ones means a valid existing install is never
# disturbed by a later attempt that happens to fail.
function Remove-StaleShortcuts {
    $target = Join-Path $InstallDir $ExeName
    if (Test-Path $target) { return }   # a real install exists; leave it alone

    foreach ($lnkPath in @(
        (Join-Path $DesktopDir "$ShortName.lnk"),
        (Join-Path $StartMenu "$ShortName.lnk")
    )) {
        if (Test-Path $lnkPath) {
            Remove-Item $lnkPath -Force -ErrorAction SilentlyContinue
        }
    }
    # The uninstall entry is equally meaningless without the program.
    Remove-Item 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS' `
        -Recurse -Force -ErrorAction SilentlyContinue
}

# ------------------------------------------------------- headless detection --
# A GUI cannot always be shown: silent/automated installs run with -Silent, and
# some execution contexts have no interactive desktop at all. In those cases the
# install still completes and the wizard is skipped, rather than the installer
# opening nothing and appearing to do nothing.
$Silent = $false
if ($args -contains '-Silent' -or $env:PHARMS_SILENT -eq '1') { $Silent = $true }

function Test-CanShowGui {
    try {
        $null = [Windows.Forms.SystemInformation]::UserInteractive
        $probe = New-Object Windows.Forms.Form
        $probe.Dispose()
        return $true
    } catch {
        return $false
    }
}

if (-not $Silent -and -not (Test-CanShowGui)) {
    Write-Host 'No interactive desktop available - running silently.'
    $Silent = $true
}

# --------------------------------------------------------------- TLS setup ---
# Force TLS 1.2. On Windows PowerShell 5.1 the default is still SSL3/TLS1.0 on
# some builds, and GitHub refuses those outright - the download fails with a
# connection error that looks like the network is down rather than a protocol
# mismatch.
try {
    [Net.ServicePointManager]::SecurityProtocol =
        [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
} catch {
    # Not fatal - PowerShell 6+ defaults to TLS 1.2 and the type may not exist.
}

# ------------------------------------------------------------------- wizard --
$welcome = @"
This will install $AppName version $Version on your computer.

  - Downloads the application from GitHub (about 15 MB)
  - Installs to your user folder - no administrator rights needed
  - Adds shortcuts to your Desktop and Start Menu
  - Keeps all patient records in $DataDir
  - Works completely offline once installed

Your records are stored outside the program folder, so reinstalling or
upgrading later will never delete your data.

An internet connection is required for this step only.

Click Install to continue.
"@

if (-not $Silent) {
    $choice = New-Dialog $welcome "$AppName Setup" @(
        @{ Text = 'Cancel';  Value = 'cancel' },
        @{ Text = 'Install'; Value = 'install' }
    )
    if ($choice -ne 'install') { exit 0 }
}

# ---------------------------------------------------------------- installing --
$ui = $null
if (-not $Silent) { $ui = Show-ProgressForm }
$tempFile = Join-Path ([IO.Path]::GetTempPath()) "PharmMS-$([Guid]::NewGuid().ToString('N')).exe"

try {
    # --- Download -----------------------------------------------------------
    Update-Progress $ui "Downloading $AppName..." 0.02 "From $DownloadUrl"

    $downloaded = $false
    $attempts = 3
    $lastError = $null
    for ($i = 1; $i -le $attempts -and -not $downloaded; $i++) {
        try {
            if ($i -gt 1) {
                Update-Progress $ui "Retrying download (attempt $i of $attempts)..." -1
                Start-Sleep -Seconds 2
            }

            # WebClient gives progress callbacks, which HttpClient does not
            # surface as simply from PowerShell. The download is one file over
            # HTTPS, so it is a good fit.
            $client = New-Object Net.WebClient
            $client.Headers.Add('User-Agent', "PharmMS-Bootstrapper/$Version")

            $received = 0
            $client.add_DownloadProgressChanged({
                param($sender, $e)
                if ($e.TotalBytesToReceive -gt 0) {
                    $fraction = 0.05 + 0.65 * ($e.BytesReceived / $e.TotalBytesToReceive)
                    $gotMb = [math]::Round($e.BytesReceived / 1MB, 1)
                    $totMb = [math]::Round($e.TotalBytesToReceive / 1MB, 1)
                    Update-Progress $ui 'Downloading...' $fraction "$gotMb MB of $totMb MB"
                }
            })

            $client.DownloadFile($DownloadUrl, $tempFile)
            $client.Dispose()
            $downloaded = $true
        } catch {
            $lastError = $_.Exception.Message
        }
    }

    if (-not $downloaded) {
        if ($ui) { $ui.Form.Close() }
        # A failed install must not leave a shortcut pointing at a program that
        # is not there. The old installer had no cleanup path at all, and a
        # machine was found with a desktop shortcut whose target did not exist -
        # the user clicks it and Windows reports a missing file, with nothing
        # explaining that the install never completed.
        Remove-StaleShortcuts
        $message = @"
Could not download $AppName.

The installer needs an internet connection for this step.

  $lastError

You can download the file manually from:
  https://github.com/$Repository/releases

and run it directly - it is the same program this installer
would have downloaded.
"@
        if ($Silent) { Write-Host $message; exit 1 }
        [Windows.Forms.MessageBox]::Show($message, "$AppName Setup", 'OK', 'Error') | Out-Null
        exit 1
    }

    # --- Verify -------------------------------------------------------------
    # TLS proves the transport, not the payload. Hashing the file against the
    # value compiled into this installer proves it is the build this
    # bootstrapper was made for, so a substituted or truncated download is
    # refused instead of installed.
    Update-Progress $ui 'Verifying the download...' 0.72

    $actual = (Get-FileHash $tempFile -Algorithm SHA256).Hash
    if ($actual -ne $PayloadHash) {
        Remove-Item $tempFile -Force -ErrorAction SilentlyContinue
        if ($ui) { $ui.Form.Close() }
        Remove-StaleShortcuts
        $message = @"
The downloaded file failed its integrity check and was NOT installed.

  expected: $($PayloadHash.Substring(0,24))...
  received: $($actual.Substring(0,24))...

This usually means the download was incomplete or was modified
in transit. Nothing has been changed on your computer.

Please try again, or download the file manually from:
  https://github.com/$Repository/releases
"@
        if ($Silent) { Write-Host $message; exit 1 }
        [Windows.Forms.MessageBox]::Show($message, "$AppName Setup", 'OK', 'Error') | Out-Null
        exit 1
    }

    Update-Progress $ui 'Download verified.' 0.78

    # --- Install ------------------------------------------------------------
    Get-Process $ShortName -ErrorAction SilentlyContinue | ForEach-Object {
        Update-Progress $ui 'Closing a running copy...' -1
        $_.CloseMainWindow() | Out-Null
        Start-Sleep -Milliseconds 700
        if (-not $_.HasExited) { $_.Kill() }
    }

    Update-Progress $ui "Creating $InstallDir..." 0.82
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null

    Update-Progress $ui 'Writing application files...' 0.88
    $target = Join-Path $InstallDir $ExeName
    Copy-Item $tempFile $target -Force
    Remove-Item $tempFile -Force -ErrorAction SilentlyContinue
    Update-Progress $ui 'Application files written.' 0.92

    # Shortcuts
    Update-Progress $ui 'Creating shortcuts...' 0.94
    $shell = New-Object -ComObject WScript.Shell
    foreach ($lnkPath in @(
        (Join-Path $DesktopDir "$ShortName.lnk"),
        (Join-Path $StartMenu "$ShortName.lnk")
    )) {
        $lnk = $shell.CreateShortcut($lnkPath)
        $lnk.TargetPath = $target
        $lnk.WorkingDirectory = $InstallDir
        $lnk.IconLocation = $target
        $lnk.Description = $AppName
        $lnk.Save()
    }
    Update-Progress $ui 'Shortcuts created.' 0.96

    # Uninstaller + Add/Remove Programs entry
    Update-Progress $ui 'Registering the uninstaller...' 0.98
    $uninstallerPath = Join-Path $InstallDir 'Uninstall-PharmMS.ps1'
    $uninstaller = @"
`$ErrorActionPreference = 'SilentlyContinue'
`$ShortName = '$ShortName'
`$InstallDir = '$InstallDir'
`$DataDir = '$DataDir'
Get-Process `$ShortName | ForEach-Object { `$_.CloseMainWindow() | Out-Null; Start-Sleep -Milliseconds 700; if (-not `$_.HasExited) { `$_.Kill() } }
Remove-Item (Join-Path ([Environment]::GetFolderPath('Desktop')) "`$ShortName.lnk") -Force
Remove-Item (Join-Path `$env:APPDATA 'Microsoft\Windows\Start Menu\Programs' "`$ShortName.lnk") -Force
Remove-Item 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS' -Force -ErrorAction SilentlyContinue
Remove-Item 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS' -Force -ErrorAction SilentlyContinue
Remove-Item `$InstallDir -Recurse -Force
Add-Type -AssemblyName System.Windows.Forms
`$answer = [Windows.Forms.MessageBox]::Show(
    "PharmMS has been removed.`n`nAlso delete all patient records in:`n`$DataDir ?`n`nThis cannot be undone.",
    'PharmMS Uninstall', 'YesNo', 'Warning')
if (`$answer -eq 'Yes') {
    Remove-Item `$DataDir -Recurse -Force
} else {
    [Windows.Forms.MessageBox]::Show("Your records were kept at:`n`$DataDir", 'PharmMS Uninstall', 'OK', 'Information') | Out-Null
}
"@
    Set-Content -Path $uninstallerPath -Value $uninstaller -Encoding UTF8

    $uninstallCmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File `"$uninstallerPath`""
    $key = 'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\PharmMS'
    New-Item -Path $key -Force | Out-Null
    Set-ItemProperty -Path $key -Name 'DisplayName'     -Value $AppName
    Set-ItemProperty -Path $key -Name 'DisplayVersion'  -Value $Version
    Set-ItemProperty -Path $key -Name 'Publisher'       -Value $Publisher
    Set-ItemProperty -Path $key -Name 'DisplayIcon'     -Value $target
    Set-ItemProperty -Path $key -Name 'InstallLocation' -Value $InstallDir
    Set-ItemProperty -Path $key -Name 'UninstallString' -Value $uninstallCmd
    Set-ItemProperty -Path $key -Name 'NoModify'        -Value 1 -Type DWord
    Set-ItemProperty -Path $key -Name 'NoRepair'        -Value 1 -Type DWord
    try {
        $size = [math]::Round((Get-Item $target).Length / 1024)
        Set-ItemProperty -Path $key -Name 'EstimatedSize' -Value $size -Type DWord
    } catch { }

    Update-Progress $ui 'Finishing...' 1.0
}
finally {
    if (Test-Path $tempFile) { Remove-Item $tempFile -Force -ErrorAction SilentlyContinue }
    if ($ui) {
        $ui.Form.Close()
        $ui.Form.Dispose()
    }
}

# ------------------------------------------------------------------- finish --
$sizeMb = [math]::Round((Get-Item (Join-Path $InstallDir $ExeName)).Length / 1MB, 1)

$done = @"
$AppName $Version has been installed.

  Program : $InstallDir\$ExeName  ($sizeMb MB)
  Records : $DataDir\pharmacy.db

You can start it from the Desktop shortcut "$ShortName" or from the
Start Menu. It opens in its own window and works without an
internet connection.

Would you like to start $ShortName now?
"@

if ($Silent) {
    Write-Host "Installed $AppName $Version to $InstallDir"
} else {
    $run = New-Dialog $done "$AppName Setup - Complete" @(
        @{ Text = 'Finish'; Value = 'finish' },
        @{ Text = 'Launch'; Value = 'launch' }
    )
    if ($run -eq 'launch') {
        Start-Process (Join-Path $InstallDir $ExeName) -WorkingDirectory $InstallDir
    }
}
'@

$setupScript = $template.
    Replace('__VERSION__', $Version).
    Replace('__HASH__', $payloadHash).
    Replace('__PAYLOAD_NAME__', $payloadName).
    Replace('__URL__', $downloadUrl).
    Replace('__REPO__', $Repository).
    Replace('__TAG__', $Tag)

Set-Content -Path $SetupPs1 -Value $setupScript -Encoding UTF8
Write-Host "    bootstrap script: $([math]::Round((Get-Item $SetupPs1).Length / 1KB, 1)) KB"

# --- 3. Compile a launcher .exe ---------------------------------------------
Write-Step 'Compiling the bootstrapper executable'

# A tiny C# stub that runs the embedded PowerShell script. Compiled with the
# C# compiler that ships with the .NET Framework, so no extra tooling is needed.
$stub = @'
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Text;

class PharmMSSetup
{
    [STAThread]
    static int Main(string[] args)
    {
        try
        {
            string temp = Path.Combine(Path.GetTempPath(), "PharmMS-Setup-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(temp);
            string script = Path.Combine(temp, "bootstrap.ps1");

            // The bootstrap script is embedded beside the stub as a resource.
            Assembly self = Assembly.GetExecutingAssembly();
            string[] names = self.GetManifestResourceNames();
            string resource = null;
            foreach (string n in names)
            {
                if (n.EndsWith("bootstrap.ps1", StringComparison.OrdinalIgnoreCase)) { resource = n; break; }
            }
            if (resource == null)
            {
                Console.Error.WriteLine("Internal error: bootstrap payload missing.");
                return 2;
            }

            using (Stream s = self.GetManifestResourceStream(resource))
            using (StreamReader r = new StreamReader(s, Encoding.UTF8))
            {
                File.WriteAllText(script, r.ReadToEnd(), new UTF8Encoding(false));
            }

            // Resolve PowerShell by ABSOLUTE PATH. A bare "powershell.exe" is
            // not reliable: it is absent from PATH on some machines, which makes
            // the installer exit silently with no window and no error message.
            string ps = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.System),
                @"WindowsPowerShell\v1.0\powershell.exe");
            if (!File.Exists(ps))
            {
                ps = "powershell.exe";
            }

            // Forward command-line arguments (notably -Silent) to the script.
            // Without this the wizard always appears and an automated install
            // hangs waiting for a click that never comes.
            StringBuilder forwarded = new StringBuilder();
            foreach (string a in args)
            {
                if (forwarded.Length > 0) { forwarded.Append(' '); }
                forwarded.Append('"').Append(a.Replace("\"", "\\\"")).Append('"');
            }

            ProcessStartInfo psi = new ProcessStartInfo();
            psi.FileName = ps;
            psi.UseShellExecute = false;
            psi.Arguments = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"" + script + "\" " + forwarded.ToString();

            Process p = Process.Start(psi);
            p.WaitForExit();

            // Clean up the temp folder. This MUST NOT fail silently.
            //
            // The previous version called Directory.Delete inside an empty
            // catch, so if the delete failed the folder was simply left behind
            // with no indication at all. A machine was found carrying four
            // orphaned PharmMS-Setup-* folders, one per run, each with the
            // bootstrap script still inside - unbounded growth in %TEMP% from
            // an installer that had already exited successfully.
            //
            // Two things can hold the folder: the PowerShell child may not have
            // fully released its file handles when WaitForExit returns, and
            // antivirus may still be scanning the script it just executed. So
            // retry briefly, and if it genuinely cannot be removed, say so on
            // stderr rather than pretending the cleanup succeeded.
            bool cleaned = false;
            for (int attempt = 0; attempt < 5 && !cleaned; attempt++)
            {
                try
                {
                    if (Directory.Exists(temp))
                    {
                        Directory.Delete(temp, true);
                    }
                    cleaned = true;
                }
                catch (IOException)
                {
                    System.Threading.Thread.Sleep(200);
                }
                catch (UnauthorizedAccessException)
                {
                    System.Threading.Thread.Sleep(200);
                }
            }
            if (!cleaned)
            {
                Console.Error.WriteLine("Note: could not remove the temporary folder " + temp);
            }

            return p.ExitCode;
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine(ex.Message);
            return 1;
        }
    }
}
'@

Set-Content -Path $StubCs -Value $stub -Encoding UTF8

# .NET Framework's csc.exe is present on every Windows machine.
$csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $csc)) {
    $csc = Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319\csc.exe'
}
if (-not (Test-Path $csc)) {
    Fail 'Could not find the C# compiler (csc.exe). A .NET Framework install is required to build the installer.'
}

$iconPath = Join-Path $BackendDir 'pharms.ico'

# The icon is a source asset, but a build should not die because one optional
# decoration is missing - csc.exe rejects a bad or absent path outright with
# "CS1583: not a valid Win32 resource file", which is a confusing way to be told
# the icon is simply not there. Warn and build without it instead.
$iconArgs = @()
if (Test-Path $iconPath) {
    # The switch and its value must be ONE command-line token: csc.exe expects
    # "/win32icon:path" and treats a separated path as an extra, unconsumed
    # argument (CS2005). Joining them into a single array element is the form
    # that works on both PowerShell 5.1 and 7.
    $iconArgs = @("/win32icon:$iconPath")
} else {
    Write-Host "    WARNING: $iconPath not found - building without a custom icon." -ForegroundColor Yellow
}

Push-Location $BuildStage
try {
    & $csc /nologo /target:winexe `
        "/out:$OutSetup" `
        "/resource:$SetupPs1,bootstrap.ps1" `
        @iconArgs `
        /reference:System.dll `
        /reference:System.Windows.Forms.dll `
        "$StubCs"
    if ($LASTEXITCODE -ne 0) { Fail 'csc.exe failed to compile the bootstrapper.' }
}
finally {
    Pop-Location
}

if (-not (Test-Path $OutSetup)) { Fail "Installer was not produced at $OutSetup" }

# --- 4. Report ---------------------------------------------------------------
$setupKb = [math]::Round((Get-Item $OutSetup).Length / 1KB, 1)

Write-Host ''
Write-Host '==============================================================' -ForegroundColor Green
Write-Host '  Bootstrapper built' -ForegroundColor Green
Write-Host '==============================================================' -ForegroundColor Green
Write-Host "  Setup file : $OutSetup"
Write-Host "  Size       : $setupKb KB  (payload is downloaded, not embedded)"
Write-Host "  Downloads  : $downloadUrl"
Write-Host "  Expects    : sha256 $($payloadHash.Substring(0, 16))..."
Write-Host ''
Write-Host '  Upload BOTH files to the same GitHub Release:' -ForegroundColor Yellow
Write-Host "    1. $OutSetup        <- the small download users click"
Write-Host "    2. $PayloadExe      <- $payloadMb MB payload, renamed to $payloadName"
Write-Host ''
Write-Host '  The setup file is useless without the payload in the same' -ForegroundColor Yellow
Write-Host '  release, and will refuse a payload whose hash differs.' -ForegroundColor Yellow
Write-Host '==============================================================' -ForegroundColor Green