"""
One-time activation tokens - the ₹500 branding unlock, v2.

WHY THIS REPLACES THE OLD NAME-BOUND KEY
----------------------------------------
The v1 key (`app/licensing.py`) was an HMAC of the pharmacy name. That makes a
key deterministic: the same shop always has the same key, so a customer who
knows one key can hand it to a friend with the same shop name, and a key can be
regenerated by anyone who learns the name. It also cannot be *spent* - nothing
records that a key has been used.

This module issues **single-use activation tokens** instead:

  * a token is generated for one sale (or generated up-front in a batch),
  * it can be activated **once**, on one machine, for the buyer's own name,
  * after activation it is permanently redeemed and cannot activate again,
  * validity is **indefinite** - there is no expiry date to fall off,
  * a new token is issued when the next payment arrives.

WHAT IS ACTUALLY ENFORCED, HONESTLY
-----------------------------------
A locally installed program cannot prevent a determined person from patching
it. Single-use is enforced by a **redemption ledger** that ships with the app:

    app/data/issued_tokens.py   ->  the signed table of tokens you have sold

Each entry carries a signature over (token, note, issued-date). The shipped build
can therefore verify that a token *was really issued by the vendor* without
carrying the signing secret - the same trade the v1 key made, and the same
honest limitation: a build must contain the issued tokens in order to check them
offline, so an attacker who reverse-engineers the executable can extract the
table and re-enable a spent token in their own copy.

What that attack does NOT give them:
  * they cannot MINT a token for an arbitrary payload - that needs the secret,
  * they cannot make a token valid for a name it was not issued with, because the
    token and the activated name are both recorded in the local audit log and the
    licence record, and re-activation for a *different* shop is refused.

If you need tokens that genuinely cannot be forged or reused, activation has to
be checked against a server you control. This module is deliberately written so
that is a drop-in change - see SERVER MODE below.

SERVER MODE (optional, off by default)
--------------------------------------
Set `PHARMS_ACTIVATION_SERVER` to a URL and activation is POSTed there instead of
being redeemed locally. The plugin sends only the token and the buyer's name -
never a patient record, never a database row. Offline, it falls back to the local
ledger so the app keeps working with no network, which is the whole point of the
product.

PLUGIN SHAPE
------------
Everything the rest of the app needs is in `service()`:

    service().issue(note)              vendor side - mint a token
    service().validate(token)          is this a token we issued?
    service().redeem(token, name)      spend it, once
    service().status()                 what is currently active
    service().revoke()                 local deactivation

`app/licensing.py` calls into this module, so the UI never changes if the
backend is swapped for a server.
"""

import hashlib
import hmac
import json
import os
import re
import secrets
from datetime import datetime, timezone

from app import db

# --- Issuer secret -----------------------------------------------------------
# Same rule as the v1 key: the shipping build can CHECK a token but must not
# carry the secret needed to CREATE one. `_BUILD_SECRET` is baked in at build
# time by build_exe.ps1; empty means "read from the environment", which is what a
# development run uses.
_TOKEN_SECRET_ENV = 'PHARMS_TOKEN_SECRET'

# Replaced by the build with a one-way verifier. Empty = not compiled in yet.
_BUILD_VERIFIER = ''

# Only used when neither of the above is configured. Public on purpose: a free
# build works out of the box, but never sell keys against it - run
# setup_licence_secret.py and rebuild with -LicenceVerifier first.
_DEV_SECRET = b'PHARMS-TOKEN-DEVELOPMENT-SECRET-not-for-sale'

ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'  # Crockford base32: no I, L, O, U

TOKEN_PREFIX = 'PMS'
# 20 base32 characters = 100 bits of entropy. Long enough that guessing is not a
# strategy, short enough that a customer can type it off a WhatsApp message.
TOKEN_BODY_LEN = 20

REDEMPTION_TABLE = 'activation_tokens'


def _secret():
    """
    The token signing secret, in resolution order:

      1. PHARMS_TOKEN_SECRET in the environment - what a build server uses.
      2. A compiled-in verifier, in which case the secret is never needed to
         CHECK a token (see validate()), only to mint one.
      3. The secret file setup_licence_secret.py wrote, outside the project.

    Why (3) matters: the setup script stores the secret in a file, so an app that
    only read the environment would sign and verify against the public
    development secret while the *issuer* signed with the real one. Every token
    you issued would then fail to verify in your own build - which is exactly
    what test_activation.py caught. Reading the file here keeps the issuer and
    the app on the same secret without anyone having to remember to export it.

    When there is genuinely nothing configured, the public development secret is
    used, and validate() reports the result as unverified rather than pretending
    it was checked.
    """
    env = os.environ.get(_TOKEN_SECRET_ENV)
    if env:
        return env.encode('utf-8')

    # A shipping build carries a verifier, not the secret, so it never reaches
    # the file path below for checking. Fall through only in source runs.
    path = _secret_file()
    if path and os.path.isfile(path):
        try:
            with open(path, encoding='utf-8') as handle:
                value = handle.read().strip()
            if value:
                return value.encode('utf-8')
        except OSError:
            pass

    return _DEV_SECRET


def _secret_file():
    """Location setup_licence_secret.py writes the token secret to."""
    base = os.environ.get('LOCALAPPDATA') or os.path.expanduser('~')
    return os.path.join(base, 'PharmMS', 'token_secret.txt')


def verifier():
    """Public verifier - safe to ship. Never reveals the secret."""
    if _BUILD_VERIFIER:
        return _BUILD_VERIFIER
    return hashlib.sha256(_secret()).hexdigest()[:16]


# --- Token minting -----------------------------------------------------------

def _b32(raw, length):
    bits = ''.join(f'{byte:08b}' for byte in raw)
    out = ''
    for i in range(0, len(bits) - (len(bits) % 5), 5):
        out += ALPHABET[int(bits[i:i + 5], 2)]
    return out[:length]


def _format_token(body):
    groups = [body[i:i + 4] for i in range(0, TOKEN_BODY_LEN, 4)]
    return TOKEN_PREFIX + '-' + '-'.join(groups)


def clean_token(text):
    """
    Canonical form of a typed token: uppercase, separators stripped, Crockford
    confusables folded. Lets a customer type 'pms ab12...' with spaces, dashes or
    an 'O' for a zero and still be accepted.
    """
    cleaned = re.sub(r'[^0-9A-Za-z]', '', (text or '')).upper()
    cleaned = (cleaned.replace('I', '1').replace('L', '1')
               .replace('O', '0').replace('U', 'V'))
    if cleaned.startswith(TOKEN_PREFIX):
        cleaned = cleaned[len(TOKEN_PREFIX):]
    return cleaned


def token_signature(body, note='', issued_at=''):
    """
    The vendor's signature over a token's payload.

    Signing the *note* and *issue date* as well as the token means an entry in
    the shipped ledger cannot be quietly edited to change what it was sold as.
    """
    payload = '|'.join([body, (note or '').strip(), (issued_at or '').strip()])
    return hmac.new(
        _secret(), payload.encode('utf-8'), hashlib.sha256
    ).hexdigest()[:24]


def mint(note='', issued_at=None):
    """
    Vendor side: create one new unused token.

    Random rather than name-derived, which is what makes it single-use: nothing
    about the token determines who may activate it, so the redemption ledger is
    the only thing that decides whether it is still good.
    """
    issued_at = issued_at or datetime.now(timezone.utc).strftime('%Y-%m-%d')
    body = _b32(secrets.token_bytes(16), TOKEN_BODY_LEN)
    return {
        'token': _format_token(body),
        'body': body,
        'note': note or '',
        'issued_at': issued_at,
        'signature': token_signature(body, note, issued_at),
    }


# --- The shipped ledger ------------------------------------------------------
# Generated by issue_tokens.py --export. Empty in a source checkout, where tokens
# are validated by re-deriving instead.
try:
    from app.data.issued_tokens import ISSUED_TOKENS as _ISSUED_TOKENS
except ImportError:
    _ISSUED_TOKENS = {}

# body -> entry, built once. Tolerates the list-of-dicts form the exporter writes.
_LEDGER = {}
if isinstance(_ISSUED_TOKENS, dict):
    for _body, _entry in _ISSUED_TOKENS.items():
        _LEDGER[clean_token(_body)] = _entry if isinstance(_entry, dict) else {
            'signature': _entry}
else:
    for _entry in (_ISSUED_TOKENS or []):
        if isinstance(_entry, dict) and _entry.get('body'):
            _LEDGER[clean_token(_entry['body'])] = _entry


def ledger_entry(body):
    """The issued-token record for a body, or None when it was not issued."""
    return _LEDGER.get(clean_token(body))


def ledger_size():
    return len(_LEDGER)


def validate(token):
    """
    Is this a token the vendor actually issued?

    Returns (ok, reason, entry). A signed ledger wins; with no ledger compiled in
    (running from source) a well-formed token is accepted so the developer can
    test, and the reason says so plainly rather than pretending it was verified.
    """
    body = clean_token(token)
    if len(body) != TOKEN_BODY_LEN:
        return False, (
            'That does not look like an activation token. Tokens are 20 '
            'characters in groups of four, like PMS-XXXX-XXXX-XXXX-XXXX.'
        ), None

    entry = ledger_entry(body)
    if entry:
        expected = token_signature(
            body, entry.get('note', ''), entry.get('issued_at', ''))
        given = entry.get('signature', '')
        if given and not hmac.compare_digest(expected, given):
            return False, (
                'That token is in the ledger but its signature does not match. '
                'The token table in this build has been altered.'
            ), None
        return True, 'Token recognised.', entry

    if _LEDGER:
        # A ledger is compiled in, so it is authoritative: a token absent from it
        # was never sold by us.
        return False, (
            'That token was not issued for this product. Check for a typing '
            'error - tokens are case-insensitive and dashes are optional.'
        ), None

    # Source checkout with no exported ledger. Accepted so the flow can be
    # exercised, and reported as unverified rather than pretending otherwise.
    return True, ('No token ledger is compiled into this build, so the token was '
                  'accepted without verifying it was issued.'), {
        'note': 'unverified (development build)', 'issued_at': ''}


# --- Redemption ledger (local, persisted) ------------------------------------

class ActivationToken(db.Model):
    """
    One row per token this installation has seen.

    This is the table that makes a token single-use *on this machine*: the token
    is written here the moment it is redeemed, and a second attempt to redeem it
    finds the row and is refused. It doubles as an audit log of who activated
    what and when, which is what a reseller actually needs when a customer says
    "my key doesn't work".
    """

    __tablename__ = REDEMPTION_TABLE

    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(64), unique=True, nullable=False, index=True)
    token_display = db.Column(db.String(80), nullable=False)
    pharmacy_name = db.Column(db.String(200), nullable=False)
    note = db.Column(db.String(200), nullable=True)
    issued_at = db.Column(db.String(40), nullable=True)
    redeemed_at = db.Column(db.DateTime, default=datetime.utcnow)
    machine = db.Column(db.String(120), nullable=True)

    def to_dict(self):
        return {
            'id': self.id,
            'token': self.token_display,
            'pharmacy_name': self.pharmacy_name,
            'note': self.note,
            'issued_at': self.issued_at,
            'redeemed_at': self.redeemed_at.isoformat() if self.redeemed_at else None,
        }


def is_redeemed(token):
    body = clean_token(token)
    if not body:
        return False
    return ActivationToken.query.filter_by(body=body).first() is not None


def redeemed_for(token):
    """Which pharmacy name this exact token was spent on, or None."""
    body = clean_token(token)
    if not body:
        return None
    row = ActivationToken.query.filter_by(body=body).first()
    return row.pharmacy_name if row else None


def mark_redeemed(token, pharmacy_name, note='', issued_at=''):
    """Record a redemption. Caller commits."""
    body = clean_token(token)
    entry = ActivationToken(
        body=body,
        token_display=_format_token(body),
        pharmacy_name=pharmacy_name,
        note=note or '',
        issued_at=issued_at or '',
        machine=_machine_id(),
    )
    db.session.add(entry)
    return entry


def redemptions():
    """Every redemption this installation has recorded, newest first."""
    return (ActivationToken.query
            .order_by(ActivationToken.redeemed_at.desc())
            .all())


def _machine_id():
    """
    A coarse, non-identifying machine label for the audit log.

    Deliberately not a hardware fingerprint: nothing here is used to lock a
    licence to a machine (tokens are machine-independent so a customer can move
    to a new PC), and a pharmacy should not have a fingerprint collected about
    it for no reason. This is the hostname and nothing else.
    """
    import socket
    try:
        return socket.gethostname()[:120]
    except Exception:
        return None


# --- Server mode (optional) --------------------------------------------------

def _server_url():
    url = (os.environ.get('PHARMS_ACTIVATION_SERVER') or '').strip()
    return url or None


def _server_redeem(token, pharmacy_name):
    """
    Ask an activation server rather than redeeming locally.

    Returns (ok, message) or (None, None) when there is no server configured or
    it could not be reached - in which case the caller falls back to the local
    ledger, because refusing to activate while offline would defeat the point of
    an offline-first product.
    """
    url = _server_url()
    if not url:
        return None, None
    try:
        import urllib.request
        payload = json.dumps({
            'token': token,
            'pharmacy_name': pharmacy_name,
        }).encode('utf-8')
        request = urllib.request.Request(
            url, data=payload,
            headers={'Content-Type': 'application/json'},
            method='POST',
        )
        with urllib.request.urlopen(request, timeout=8) as response:
            body = json.loads(response.read().decode('utf-8'))
        if body.get('ok'):
            return True, body.get('message') or 'Activated.'
        return False, body.get('message') or 'The activation server refused that token.'
    except Exception:
        return None, None


# --- The service the rest of the app talks to --------------------------------

class ActivationService:
    """
    The plugin boundary.

    `app/licensing.py` only ever calls these methods, so swapping the local ledger
    for a server (or a reseller portal) is a change here and nowhere else.
    """

    #: what a customer pays, in rupees - surfaced in the UI
    price_inr = 500

    #: tokens never expire. Stated as a property so the UI cannot drift.
    validity = 'indefinite'

    def issue(self, note=''):
        """Vendor side: mint a token. Not shipped - see tools/issue_tokens.py."""
        return mint(note)

    def validate(self, token):
        return validate(token)

    def is_redeemed(self, token):
        return is_redeemed(token)

    def redeem(self, token, pharmacy_name):
        """
        Spend a token on a pharmacy name. Returns (ok, message).

        Order of refusal, most specific first, so the customer gets the reason
        that is actually true rather than a generic failure:

          1. malformed           -> tell them the shape
          2. not issued by us     -> typo or forged
          3. already spent here   -> single-use, and say when/by whom
          4. server says no       -> only when a server is configured and reachable
          5. too many activations -> unlimited while unlicensed is free, but a
                                     licence is for one pharmacy
        """
        name = (pharmacy_name or '').strip()
        if not name:
            return False, 'Enter your pharmacy name.'

        ok, reason, entry = validate(token)
        if not ok:
            return False, reason

        body = clean_token(token)

        if is_redeemed(body):
            spent_on = redeemed_for(body)
            if spent_on and spent_on.strip().lower() == name.lower():
                # Re-entering the same token on the same installation is not a
                # new activation - it is the same licence. Allow it so a customer
                # can re-apply after clearing branding, but say it was already used.
                return True, (
                    f"That token has already been activated on this computer for "
                    f"{spent_on}. Reactivating the same licence."
                )
            return False, (
                'That activation token has already been used'
                + (f' for "{spent_on}"' if spent_on else '')
                + '. Tokens are single-use: a new one is issued when the next '
                  'payment is received.'
            )

        # Server mode, when configured and reachable.
        server_ok, server_message = _server_redeem(body, name)
        if server_ok is False:
            return False, server_message
        if server_ok is None and _server_url():
            # Configured but unreachable: fall through to the local ledger and
            # say so, rather than blocking an offline pharmacy.
            pass

        mark_redeemed(
            body, name,
            note=(entry or {}).get('note', ''),
            issued_at=(entry or {}).get('issued_at', ''),
        )
        return True, (
            f'Activation token accepted. This copy of the application is now '
            f'licensed to {name}, indefinitely.'
        )

    def status(self):
        """What the UI needs to render the licensing panel."""
        return {
            'verifier': verifier(),
            'token_format': 'PMS-XXXX-XXXX-XXXX-XXXX',
            'price_inr': self.price_inr,
            'validity': self.validity,
            'ledger_size': ledger_size(),
            'server_mode': bool(_server_url()),
            'redemptions': [row.to_dict() for row in redemptions()],
        }


_SERVICE = ActivationService()


def service():
    """
    The activation plugin.

    Replaced wholesale by a different implementation (server-backed, reseller
    portal) without any other module changing.
    """
    return _SERVICE